<?php

 $title = 'Company List';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('company', array('action'=>'add'));?>">Add new company</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Type</th>
     <th>Activity</th>
     <th>Contact</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($companys as $company) : ?>
 <tr>
     <td>
        <a href="<?php echo $this->url('company', array('action'=>'view', 'id' => $company->id));?>">
            <?php echo $this->escapeHtml($company->name);?>
        </a>
    </td>
     <td><?php echo $this->escapeHtml($company->type);?></td>
     <td><?php echo $this->escapeHtml($company->activity);?></td>
     <td><?php echo $this->escapeHtml($company->contact);?></td>
     <td>
         <a href="<?php echo $this->url('company',
             array('action'=>'edit', 'id' => $company->id));?>">Edit</a>
         <a href="<?php echo $this->url('company',
             array('action'=>'delete', 'id' => $company->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>