<?php

 $title = 'Add new company Main';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>You can register new company</p>
 <?php
 $form->setAttribute('action', $this->url('company', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo '<br>';
 echo $this->formRow($form->get('type'));
  echo '<br>';
 echo $this->formRow($form->get('activity'));
  echo '<br>';
 echo $this->formRow($form->get('contact'));
  echo '<br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();